### ISSUE TITLE
ASCII/UTF-8 problem, try to catch non UTF-8 characters.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ydiffy#1]
See: https://github.com/zdavatz/oddb.org/issues/194

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/212548856-08512bdb-8798-4175-8b23-478af7c1b8b7.png)

**Comment by ngiger** [comment]
On oddb_ci2 I did a ` xmllint --pretty 1 ./data/details/59322_fi_de.xml` where the file dates from March 19,2021.
Comparing it with `./data/details/59322_fi_de_Crilomus__problem.xml` from Jan 5, 2023 I found that the newer file contained `<atcCode>L04AD02</atcCode>` which looks reasonable.
The old file howerver contained ` <atcCode>Codice ATC L04AD02FarmacodinamicaTacrolimus &amp;egrav</atcCode>`which is clearly not in the expected format and contains the non UTF-8 `&amp;egrav`
Will try to make a test case with this content.

**Comment by zdavatz** [comment]
this now works with ydiffy-0.0.5
